export default [
  // UI
  'TOGGLE_SIDE_BAR',

  // API
  'LOGIN',
  'GET_ACCOUNT_INFO',
  'GET_ROLES',
  'ADD_ROLE',
  'UPDATE_ROLE',
  'DELETE_ROLE',
  'GET_PERMISSIONS',

  'GET_ALL_ADMIN',
  'DELETE_ADMIN',
  'ADD_SUB_ADMIN',
  'UPDATE_ADMIN',

  'GET_APPLICATIONS',
  'UPDATE_APPLICATION',
  'MOVE_APPLICATIONS',
  'SEND_MAIL_WRONG_PASSPORT',
  'GET_SEND_MAIL_LOG',

  'GET_COUNTRIES',
  'GET_BUSINESS_SYSTEM',

  // Store
  'SET_APPLICATION_STORE_PARAMS',
  'RESET_ADMIN',
  'RESET_APPLICATION_STORE'
]
